# Your application's name
appname: "bookstore"

# The default layout to use for your application (located in views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

session: Simple

template: "template_toolkit"
engines:
   template:
     template_toolkit:
       start_tag: '<%'
       end_tag:   '%>'

plugins:
   Paginator:
     frame_size: 1
     page_size: 3
   Captcha:
     new:
       width: 160
       height: 75
       lines: 5
       gd_font: 'giant'
     create: [ 'normal', 'default' ]
     out:
       force: 'png'
     particle: [ 100 ]
   DBIC:
     bookstore:
       dsn: "dbi:SQLite:dbname=bookstore.db"
